# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'autolainaus.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDateEdit, QHeaderView,
    QLabel, QLineEdit, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QTabWidget, QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(888, 642)
        self.actionMuokkaa = QAction(MainWindow)
        self.actionMuokkaa.setObjectName(u"actionMuokkaa")
        self.actionTietoja_ohjelmasta = QAction(MainWindow)
        self.actionTietoja_ohjelmasta.setObjectName(u"actionTietoja_ohjelmasta")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 911, 591))
        self.lainaajat = QWidget()
        self.lainaajat.setObjectName(u"lainaajat")
        self.henkilotunnusLabel = QLabel(self.lainaajat)
        self.henkilotunnusLabel.setObjectName(u"henkilotunnusLabel")
        self.henkilotunnusLabel.setGeometry(QRect(30, 20, 150, 25))
        font = QFont()
        font.setPointSize(14)
        self.henkilotunnusLabel.setFont(font)
        self.etunimiLabel = QLabel(self.lainaajat)
        self.etunimiLabel.setObjectName(u"etunimiLabel")
        self.etunimiLabel.setGeometry(QRect(30, 60, 150, 25))
        self.etunimiLabel.setFont(font)
        self.sukunimiLabel = QLabel(self.lainaajat)
        self.sukunimiLabel.setObjectName(u"sukunimiLabel")
        self.sukunimiLabel.setGeometry(QRect(30, 110, 150, 25))
        self.sukunimiLabel.setFont(font)
        self.ajoneuvoluokkaLabel = QLabel(self.lainaajat)
        self.ajoneuvoluokkaLabel.setObjectName(u"ajoneuvoluokkaLabel")
        self.ajoneuvoluokkaLabel.setGeometry(QRect(30, 160, 150, 25))
        self.ajoneuvoluokkaLabel.setFont(font)
        self.henkilotunnusLineEdit = QLineEdit(self.lainaajat)
        self.henkilotunnusLineEdit.setObjectName(u"henkilotunnusLineEdit")
        self.henkilotunnusLineEdit.setGeometry(QRect(200, 20, 150, 25))
        self.henkilotunnusLineEdit.setFont(font)
        self.etunimiLineEdit = QLineEdit(self.lainaajat)
        self.etunimiLineEdit.setObjectName(u"etunimiLineEdit")
        self.etunimiLineEdit.setGeometry(QRect(200, 60, 150, 25))
        self.etunimiLineEdit.setFont(font)
        self.sukunimiLineEdit = QLineEdit(self.lainaajat)
        self.sukunimiLineEdit.setObjectName(u"sukunimiLineEdit")
        self.sukunimiLineEdit.setGeometry(QRect(200, 110, 150, 25))
        self.sukunimiLineEdit.setFont(font)
        self.ajoneuvoluokkaLineEdit = QLineEdit(self.lainaajat)
        self.ajoneuvoluokkaLineEdit.setObjectName(u"ajoneuvoluokkaLineEdit")
        self.ajoneuvoluokkaLineEdit.setGeometry(QRect(200, 160, 150, 25))
        self.ajoneuvoluokkaLineEdit.setFont(font)
        self.lainaajatLabel = QLabel(self.lainaajat)
        self.lainaajatLabel.setObjectName(u"lainaajatLabel")
        self.lainaajatLabel.setGeometry(QRect(30, 270, 200, 25))
        self.lainaajatLabel.setFont(font)
        self.lainaajatTableWidget = QTableWidget(self.lainaajat)
        if (self.lainaajatTableWidget.columnCount() < 5):
            self.lainaajatTableWidget.setColumnCount(5)
        if (self.lainaajatTableWidget.rowCount() < 8):
            self.lainaajatTableWidget.setRowCount(8)
        self.lainaajatTableWidget.setObjectName(u"lainaajatTableWidget")
        self.lainaajatTableWidget.setGeometry(QRect(30, 305, 530, 261))
        self.lainaajatTableWidget.setRowCount(8)
        self.lainaajatTableWidget.setColumnCount(5)
        self.tallennaLainaajatPushButton = QPushButton(self.lainaajat)
        self.tallennaLainaajatPushButton.setObjectName(u"tallennaLainaajatPushButton")
        self.tallennaLainaajatPushButton.setGeometry(QRect(460, 210, 100, 30))
        self.tallennaLainaajatPushButton.setFont(font)
        self.sahkopostiLineEdit = QLineEdit(self.lainaajat)
        self.sahkopostiLineEdit.setObjectName(u"sahkopostiLineEdit")
        self.sahkopostiLineEdit.setGeometry(QRect(200, 210, 150, 25))
        self.sahkopostiLabel = QLabel(self.lainaajat)
        self.sahkopostiLabel.setObjectName(u"sahkopostiLabel")
        self.sahkopostiLabel.setGeometry(QRect(30, 210, 150, 25))
        self.sahkopostiLabel.setFont(font)
        self.tabWidget.addTab(self.lainaajat, "")
        self.autot = QWidget()
        self.autot.setObjectName(u"autot")
        self.merkkiLabel = QLabel(self.autot)
        self.merkkiLabel.setObjectName(u"merkkiLabel")
        self.merkkiLabel.setGeometry(QRect(30, 20, 150, 25))
        self.merkkiLabel.setFont(font)
        self.malliLabel = QLabel(self.autot)
        self.malliLabel.setObjectName(u"malliLabel")
        self.malliLabel.setGeometry(QRect(30, 70, 150, 25))
        self.malliLabel.setFont(font)
        self.vuosimalliLabel = QLabel(self.autot)
        self.vuosimalliLabel.setObjectName(u"vuosimalliLabel")
        self.vuosimalliLabel.setGeometry(QRect(30, 120, 150, 25))
        self.vuosimalliLabel.setFont(font)
        self.rekisterinumeroLabel = QLabel(self.autot)
        self.rekisterinumeroLabel.setObjectName(u"rekisterinumeroLabel")
        self.rekisterinumeroLabel.setGeometry(QRect(30, 170, 150, 25))
        self.rekisterinumeroLabel.setFont(font)
        self.henkilomaaraLabel = QLabel(self.autot)
        self.henkilomaaraLabel.setObjectName(u"henkilomaaraLabel")
        self.henkilomaaraLabel.setGeometry(QRect(30, 220, 150, 25))
        self.henkilomaaraLabel.setFont(font)
        self.autoluetteloLabel = QLabel(self.autot)
        self.autoluetteloLabel.setObjectName(u"autoluetteloLabel")
        self.autoluetteloLabel.setGeometry(QRect(30, 280, 150, 25))
        self.autoluetteloLabel.setFont(font)
        self.autoluetteloTableWidget = QTableWidget(self.autot)
        if (self.autoluetteloTableWidget.columnCount() < 7):
            self.autoluetteloTableWidget.setColumnCount(7)
        if (self.autoluetteloTableWidget.rowCount() < 8):
            self.autoluetteloTableWidget.setRowCount(8)
        self.autoluetteloTableWidget.setObjectName(u"autoluetteloTableWidget")
        self.autoluetteloTableWidget.setGeometry(QRect(30, 319, 730, 241))
        self.autoluetteloTableWidget.setRowCount(8)
        self.autoluetteloTableWidget.setColumnCount(7)
        self.merkkiLineEdit = QLineEdit(self.autot)
        self.merkkiLineEdit.setObjectName(u"merkkiLineEdit")
        self.merkkiLineEdit.setGeometry(QRect(200, 20, 150, 25))
        self.merkkiLineEdit.setFont(font)
        self.malliLineEdit = QLineEdit(self.autot)
        self.malliLineEdit.setObjectName(u"malliLineEdit")
        self.malliLineEdit.setGeometry(QRect(200, 70, 150, 25))
        self.malliLineEdit.setFont(font)
        self.vuosimalliLineEdit = QLineEdit(self.autot)
        self.vuosimalliLineEdit.setObjectName(u"vuosimalliLineEdit")
        self.vuosimalliLineEdit.setGeometry(QRect(200, 120, 150, 25))
        self.vuosimalliLineEdit.setFont(font)
        self.rekisterinumeroLineEdit = QLineEdit(self.autot)
        self.rekisterinumeroLineEdit.setObjectName(u"rekisterinumeroLineEdit")
        self.rekisterinumeroLineEdit.setGeometry(QRect(200, 170, 150, 25))
        self.rekisterinumeroLineEdit.setFont(font)
        self.henkilomaaraLineEdit = QLineEdit(self.autot)
        self.henkilomaaraLineEdit.setObjectName(u"henkilomaaraLineEdit")
        self.henkilomaaraLineEdit.setGeometry(QRect(200, 220, 150, 25))
        self.henkilomaaraLineEdit.setFont(font)
        self.tallennaAutotPushButton = QPushButton(self.autot)
        self.tallennaAutotPushButton.setObjectName(u"tallennaAutotPushButton")
        self.tallennaAutotPushButton.setGeometry(QRect(590, 220, 100, 30))
        self.tallennaAutotPushButton.setFont(font)
        self.ajoneuvotyyppiLabel = QLabel(self.autot)
        self.ajoneuvotyyppiLabel.setObjectName(u"ajoneuvotyyppiLabel")
        self.ajoneuvotyyppiLabel.setGeometry(QRect(410, 20, 150, 25))
        self.ajoneuvotyyppiLabel.setFont(font)
        self.ajoneuvotyyppiComboBox = QComboBox(self.autot)
        self.ajoneuvotyyppiComboBox.setObjectName(u"ajoneuvotyyppiComboBox")
        self.ajoneuvotyyppiComboBox.setGeometry(QRect(590, 20, 150, 25))
        self.vaihteistotyyppiLabel = QLabel(self.autot)
        self.vaihteistotyyppiLabel.setObjectName(u"vaihteistotyyppiLabel")
        self.vaihteistotyyppiLabel.setGeometry(QRect(410, 70, 150, 25))
        self.vaihteistotyyppiLabel.setFont(font)
        self.vaihteistotyyppiComboBox = QComboBox(self.autot)
        self.vaihteistotyyppiComboBox.setObjectName(u"vaihteistotyyppiComboBox")
        self.vaihteistotyyppiComboBox.setGeometry(QRect(590, 70, 150, 25))
        self.tabWidget.addTab(self.autot, "")
        self.raportit = QWidget()
        self.raportit.setObjectName(u"raportit")
        self.raporttiComboBox = QComboBox(self.raportit)
        self.raporttiComboBox.setObjectName(u"raporttiComboBox")
        self.raporttiComboBox.setGeometry(QRect(30, 80, 150, 25))
        self.raporttiComboBox.setFont(font)
        self.esikatseluTableWidget = QTableWidget(self.raportit)
        self.esikatseluTableWidget.setObjectName(u"esikatseluTableWidget")
        self.esikatseluTableWidget.setGeometry(QRect(30, 280, 600, 275))
        self.alkaaLabel = QLabel(self.raportit)
        self.alkaaLabel.setObjectName(u"alkaaLabel")
        self.alkaaLabel.setGeometry(QRect(30, 140, 150, 25))
        self.alkaaLabel.setFont(font)
        self.paattyylabel = QLabel(self.raportit)
        self.paattyylabel.setObjectName(u"paattyylabel")
        self.paattyylabel.setGeometry(QRect(240, 140, 150, 25))
        self.paattyylabel.setFont(font)
        self.tulostaPushButton = QPushButton(self.raportit)
        self.tulostaPushButton.setObjectName(u"tulostaPushButton")
        self.tulostaPushButton.setGeometry(QRect(440, 220, 100, 30))
        self.tulostaPushButton.setFont(font)
        self.esikatseluLabel = QLabel(self.raportit)
        self.esikatseluLabel.setObjectName(u"esikatseluLabel")
        self.esikatseluLabel.setGeometry(QRect(30, 250, 150, 25))
        self.esikatseluLabel.setFont(font)
        self.raporttiLabel = QLabel(self.raportit)
        self.raporttiLabel.setObjectName(u"raporttiLabel")
        self.raporttiLabel.setGeometry(QRect(30, 30, 150, 25))
        self.raporttiLabel.setFont(font)
        self.alkaaDateEdit = QDateEdit(self.raportit)
        self.alkaaDateEdit.setObjectName(u"alkaaDateEdit")
        self.alkaaDateEdit.setGeometry(QRect(30, 180, 150, 25))
        self.alkaaDateEdit.setFont(font)
        self.alkaaDateEdit.setCalendarPopup(True)
        self.paattyyDateEdit = QDateEdit(self.raportit)
        self.paattyyDateEdit.setObjectName(u"paattyyDateEdit")
        self.paattyyDateEdit.setGeometry(QRect(240, 180, 150, 25))
        self.paattyyDateEdit.setFont(font)
        self.paattyyDateEdit.setCalendarPopup(True)
        self.tabWidget.addTab(self.raportit, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 888, 21))
        self.menuAsetukset = QMenu(self.menubar)
        self.menuAsetukset.setObjectName(u"menuAsetukset")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuAsetukset.menuAction())
        self.menuAsetukset.addAction(self.actionMuokkaa)
        self.menuAsetukset.addAction(self.actionTietoja_ohjelmasta)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionMuokkaa.setText(QCoreApplication.translate("MainWindow", u"Muokkaa...", None))
#if QT_CONFIG(shortcut)
        self.actionMuokkaa.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionTietoja_ohjelmasta.setText(QCoreApplication.translate("MainWindow", u"Tietoja ohjelmasta...", None))
        self.henkilotunnusLabel.setText(QCoreApplication.translate("MainWindow", u"Henkil\u00f6tunnus", None))
        self.etunimiLabel.setText(QCoreApplication.translate("MainWindow", u"Etunimi", None))
        self.sukunimiLabel.setText(QCoreApplication.translate("MainWindow", u"Sukunimi", None))
        self.ajoneuvoluokkaLabel.setText(QCoreApplication.translate("MainWindow", u"Ajoneuvoluokka", None))
        self.lainaajatLabel.setText(QCoreApplication.translate("MainWindow", u"Rekister\u00f6idyt lainaajat", None))
        self.tallennaLainaajatPushButton.setText(QCoreApplication.translate("MainWindow", u"Tallenna", None))
        self.sahkopostiLabel.setText(QCoreApplication.translate("MainWindow", u"S\u00e4hk\u00f6posti", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lainaajat), QCoreApplication.translate("MainWindow", u"Lainaajat", None))
        self.merkkiLabel.setText(QCoreApplication.translate("MainWindow", u"Merkki", None))
        self.malliLabel.setText(QCoreApplication.translate("MainWindow", u"Malli", None))
        self.vuosimalliLabel.setText(QCoreApplication.translate("MainWindow", u"Vuosimalli", None))
        self.rekisterinumeroLabel.setText(QCoreApplication.translate("MainWindow", u"Rekisterinumero", None))
        self.henkilomaaraLabel.setText(QCoreApplication.translate("MainWindow", u"Henkil\u00f6m\u00e4\u00e4r\u00e4", None))
        self.autoluetteloLabel.setText(QCoreApplication.translate("MainWindow", u"Autoluettelo", None))
        self.tallennaAutotPushButton.setText(QCoreApplication.translate("MainWindow", u"Tallenna", None))
        self.ajoneuvotyyppiLabel.setText(QCoreApplication.translate("MainWindow", u"Ajoneuvotyyppi", None))
        self.vaihteistotyyppiLabel.setText(QCoreApplication.translate("MainWindow", u"Vaihteistotyyppi", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.autot), QCoreApplication.translate("MainWindow", u"Autot", None))
        self.alkaaLabel.setText(QCoreApplication.translate("MainWindow", u"Alkaa", None))
        self.paattyylabel.setText(QCoreApplication.translate("MainWindow", u"P\u00e4\u00e4ttyy", None))
        self.tulostaPushButton.setText(QCoreApplication.translate("MainWindow", u"Tulosta", None))
        self.esikatseluLabel.setText(QCoreApplication.translate("MainWindow", u"Esikatselu", None))
        self.raporttiLabel.setText(QCoreApplication.translate("MainWindow", u"Raportti", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.raportit), QCoreApplication.translate("MainWindow", u"Raportit", None))
        self.menuAsetukset.setTitle(QCoreApplication.translate("MainWindow", u"Asetukset", None))
    # retranslateUi

